default_platform(:ios)

platform :ios do
  desc "CI: build and upload to TestFlight"
  lane :ci do
    sh "flutter pub get"
    sh "cd ios && pod install --repo-update"

    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_KEY_ID'],
      issuer_id: ENV['APP_STORE_ISSUER_ID'],
      key_filepath: 'ios/AuthKey.p8'
    )

    build_app(
      workspace: "ios/Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      api_key: api_key
    )

    upload_to_testflight(api_key: api_key)
  end
end
